### ISSUE TITLE
Coverage function to turn df into Rle?

### ISSUE THREAD

**Issue by endrebak** [phaverty/RLEVectors.jl#12]
The original IRanges library has a function called coverage to turn interval data into an Rle. Will you consider implementing a coverage function?

Thanks for the library, btw.

**Comment by phaverty** [comment]
Hi Endre,

I'm glad you are benefitting from the package. My GenomicVectors.jl package
has a coverage method that returns an RleVector. I think there is room for
optimization. Please let me know how it works for you.

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by endrebak** [comment]
Thanks. I searched the wrong repo then. 

My intention is to translate it into Cython - I'll be sure to give you credit. I have an implementation myself, but it uses two heaps.

**Comment by endrebak** [comment]
Julia looks nice! I need to learn it to be able to understand how you can write a coverage-function as simply as this, because I am guessing you are not instantiating a vector of chromosome length:

```
function coverage(gr::AbstractGenomicVector)
    out = RLEVector(0, last(chr_ends(gr)))
    for (s,e) in eachrange(gr)
        out[s:e] += 1
    end
    out
end
```

**Comment by phaverty** [comment]
Hi Endre,

The subtypes of AbstractGenomicVector contain a GenomeInfo object, which
contains the chromosome lengths (actually, the cumsum of the lengths). This
allows AbstractGenomicVector to store the genome base positions as the
offset from the first base of chr1. That way we can do (almost) everything
on one scale without worrying about chromosomes. And since julia has 64bit
ints we can have one RLE that spans the genome. (R only has 32 bit, signed
integers, which are to small to hold an index into the last few
chromosomes).

Pete

____________________
Peter M. Haverty, Ph.D.
Genentech, Inc.
phaverty@gene.com

**Comment by endrebak** [comment]
This is my dataframe based attempt, just in case anyone is interested. It can also take a value column to create an Rle of scores (e.g. from bed files) instead of just raw coverage. It it not purely vectorized, as the grouby is a cython/C-based operation. 

```python
def coverage(ranges, value_col=None):

    try:
        df = ranges.df
    except:
        df = ranges

    df = df.sort_values("Start End".split())

    if value_col:
        starts = df[["Start"] + [value_col]]
        ends = df[["End"] + [value_col]]
        # spurious warning
        pd.options.mode.chained_assignment = None
        ends.loc[:, value_col] = ends.loc[:, value_col] * - 1
        pd.options.mode.chained_assignment = "warn"
        columns = ["Position"] + [value_col]
    else:
        starts = pd.concat([df.Start, pd.Series(np.ones(len(df)))], axis=1)
        ends = pd.concat([df.End, -1 * pd.Series(np.ones(len(df)))], axis=1)
        columns = "Position Value".split()
        value_col = "Value"

    starts.columns, ends.columns = columns, columns
    runs = pd.concat([starts, ends], ignore_index=True)
    values = runs.groupby("Position").sum().reset_index().drop_duplicates()[value_col]
    first_value = values.iloc[0] if starts.Position.min() == 0 else 0
    run_lengths = (runs.Position - runs.Position.shift().fillna(0))[:-1]

    values = values.cumsum().shift()
    values[0] = first_value

    return Rle(run_lengths, values)
```
