### ISSUE TITLE
Would it be possible to separate R functionalities of RLEVectors into a separate package?

### ISSUE THREAD

**Issue by xiaodaigh** [phaverty/RLEVectors.jl#22]
When I load RLEVectors, the RCall package is activated with R startup messages. Also RCall in temperamental, the Julia portion of the code might be working but a user can't use your package unless they solve the RCall.jl issues. So including it when it's not absolutely necessary for Julia usage can become problematic.

**Comment by phaverty** [comment]
RCall can be a tough dependency. I've had trouble recently too. I'll think about moving the RCall stuff to a separate package. Maybe the RCall stuff for R to Julia and back translation for GenomicVectors.jl and future BioConductor-ish packages would go there too. Thanks for the suggestion.

**Comment by phaverty** [comment]
Aha! Requires.jl and conditional dependency to the rescue ...

**Comment by phaverty** [comment]
I've made RCall a conditional dependency using Requires.jl. Please try this out with the master branch. If it looks OK, I'll make a new release.

**Comment by xiaodaigh** [comment]
Looks pretty good. Worked great. #23 would be great

**Comment by phaverty** [comment]
@JuliaRegistrator register
