### ISSUE TITLE
Implement `allowmissing` and `disallowmissing`

### ISSUE THREAD

**Issue by xiaodaigh** [phaverty/RLEVectors.jl#23]
After creating an `vec::RLEVector{T}` calling `allowmissing(vec)`  changes the type of `vec` to `Vector{T}`. Can we implement `allowmissing` and `disallowmissing` so that calling them does not eliminate the advantage of using `RLEVectors`?

**Comment by phaverty** [comment]
Yes, thanks, good idea. I'll look into how to do that. I'd be happy to consider a PR too :-)

**Comment by xiaodaigh** [comment]
Yeah. I devote Sunday morning to OS's but it's a bit down my list atm. Don't count on it any time soon :)

**Comment by phaverty** [comment]
OK, please give master a try. You can't actually put missing in an RLEVector yet, but you can call `allowmissing` and `disallowmissing` and get the type to change.  I'll figure out how to get the outer constructors to work with missing value and add a `skipmissing` iterator. Are there other things I'm leaving out?

**Comment by Zymergen-phaverty** [comment]
You can use missing in RLEVectors now.  I've got some unrelated breakage with julia 1.2 to fix and then I'll do a release.

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by Zymergen-phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by Zymergen-phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register
