### ISSUE TITLE
broadcast setting of a subset is broken

### ISSUE THREAD

**Issue by phaverty** [phaverty/RLEVectors.jl#25]
rle[2:5] .= 7 breaks tests

**Comment by Zymergen-phaverty** [comment]
Modernized broadcasting in a recent commit helps many cases, but .= is still broken.

@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
DistributedArrays has some stuff that may make good examples. e.g. they have a method on distributed that recursively makes all the arrays into DistributedArrays. We will want something like this to normalize the number of runs between pairs of RLE or make AbstractVectors in to RLEVectors
