### ISSUE TITLE
Creating RLEVector from BitVector is wrong

### ISSUE THREAD

**Issue by Zymergen-phaverty** [phaverty/RLEVectors.jl#30]
Treats BitVector as a scalar rather than an array.

**Comment by Zymergen-phaverty** [comment]
julia> RLEVector( 1:100 .> 50 )
RLEVector{BitArray{1},Int64}
 Run values: BitArray{1}[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0  …  1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]
 Run ends: [1]

julia>

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register

**Comment by phaverty** [comment]
@JuliaRegistrator register
