### ISSUE TITLE
show method output is duplicated

### ISSUE THREAD

**Issue by MattBrauer** [phaverty/RLEVectors.jl#4]
-> runs = RLEVector(inSetS)
-> runs
run values: [false,true,false … true,false,true]
run ends:   [22170,22172,22182 … 262112,262129,262144]
run values: [false,true,false … true,false,true]
run ends:   [22170,22172,22182 … 262112,262129,262144]

**Comment by phaverty** [comment]
Thank you for the report. I can't duplicate this locally. What version of the package and julia did you use for this example?
