### ISSUE TITLE
logical indices on RLEVector{String} failed with UndefRefError

### ISSUE THREAD

**Issue by Marlin-Na** [phaverty/RLEVectors.jl#44]
I got the following error when using logical indices on a RLEVector{String}

```
julia> a = RLEVectors.RLEVector(["aa", "bb", "cc"])

julia> a[[true, false, true]]
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex at ./array.jl:809 [inlined]
 [2] setindex!(::RLEVectors.RLEVector{String,Int64}, ::String, ::Int64) at /Users/x/.julia/packages/RLEVectors/ZW6hy/src/indexing.jl:74
 [3] macro expansion at ./multidimensional.jl:772 [inlined]
 [4] macro expansion at ./cartesian.jl:64 [inlined]
 [5] macro expansion at ./multidimensional.jl:767 [inlined]
 [6] _unsafe_getindex! at ./multidimensional.jl:762 [inlined]
 [7] _unsafe_getindex(::IndexLinear, ::RLEVectors.RLEVector{String,Int64}, ::Base.LogicalIndex{Int64,Array{Bool,1}}) at ./multidimensional.jl:757
 [8] _getindex at ./multidimensional.jl:743 [inlined]
 [9] getindex(::RLEVectors.RLEVector{String,Int64}, ::Array{Bool,1}) at ./abstractarray.jl:1060
 [10] top-level scope at REPL[8]:1
```

Interestingly, logical indices on RLEVector{Int64} or any other type works

```
julia> b = RLEVectors.RLEVector([1,2,3])

julia> b[[true, false, true]]
RLEVectors.RLEVector{Int64,Int64}
 Run values: [1, 3]
 Run ends: [1, 2]
```

**Comment by Marlin-Na** [comment]
I guess this is due to the fact that `similar(a)` creates undefined reference. For example:
```
julia> similar(a)
RLEVectors.RLEVector{String,Int64}
 Run values: [#undef]
 Run ends: [3]

julia> similar(a).runvalues[1]
ERROR: UndefRefError: access to undefined reference
Stacktrace:
 [1] getindex(::Array{String,1}, ::Int64) at ./array.jl:809
 [2] top-level scope at REPL[40]:1
```

**Comment by phaverty** [comment]
Thank you for this report. I remember being unsure what to do with empty RLEVectors. `runends` has to be of length one to hold the length of the uncompressed vector. So, `runvalues` has to be of length one. I didn't want to want to make `runvalues` a Union of Missing and the target type (e.g. String), hence the undef. I thought this was a behavior similar to normal Vectors. I'll have another look.

**Comment by Marlin-Na** [comment]
@phaverty I guess it's fine to use `undef` and as you said this is similar to normal vectors. I looked into this a little bit and found that my issue may be fixed with the following patch, where `isassigned` is used to check whether one element of the array is `undef`

```
diff --git a/src/indexing.jl b/src/indexing.jl
index 3c9c26e..1103e61 100644
--- a/src/indexing.jl
+++ b/src/indexing.jl
@@ -71,6 +71,9 @@ end

 function Base.setindex!(rle::RLEVector, value, i::Integer)
     run = ind2run(rle, i)
+    if ! isassigned(rle.runvalues, run)
+        rle.runvalues[run] = value # substitute undef with valid value from user
+    end
     runvalue = rle.runvalues[run]
     runend = rle.runends[run]
     #value == runvalue && return rle # replace with same value, no-op
```

Let me know whether you like this solution or not.

**Comment by phaverty** [comment]
OK, I see how this happens now. `getindex` with logical indices calls some of the `AbstractVector` code which makes an empty `RLEVector` and fills it one element at a time. The `setindex!` method for `RLEVector` fails when trying to compare the incoming value with the existing value (which is undef). The underlying problem is that I need a specialized `getindex` for `RLEVector` when the indices are `Vector{Bool}`. I'll add that.

**Comment by Marlin-Na** [comment]
@phaverty  I think it still worth fixing `setindex!` to account of `undef` (checking with `isassigned`). Things like broadcast, copyto! would rely on that. For example:

```
julia> rle = RLEVector(["aa", "bb", "bb"])

julia> rle .* "suffix"
ERROR: UndefRefError: access to undefined reference
```
and
```
julia> copyto!(similar(rle), collect(rle))
ERROR: UndefRefError: access to undefined reference
```

**Comment by phaverty** [comment]
Yes, it is probably still worth doing. I'll either add the `isassigned`
into `setindex!` or come up with a special way of filling an empty
`RLEVector`.

**Comment by phaverty** [comment]
I'm sure there is a lot that could be done to optimize the broadcast stuff,
so I'll be looking at that specifically. Right now I just fall back to the
default stuff which iterates over the whole array. It should be possible to
have `broadcast` be more like `map` where scalars just get applied to each
runvalue once.
