### ISSUE TITLE
Broadcast for RLEVectors doubles invocation of the function

### ISSUE THREAD

**Issue by Marlin-Na** [phaverty/RLEVectors.jl#45]
I checked the broadcast behavior a little bit:

```
x = RLEVector([1,1,1,2,2,3]) # 6 elements, 3 runs
function simple_add(x)
    println("function invoked")
    x + 100
end
simple_add.(x)
```

Interestingly, code snippet above invokes `simple_add` for 12 times, not 6 (vector length) nor 3 (number of runs).

```
function invoked
function invoked
function invoked
function invoked
function invoked
function invoked
function invoked
function invoked
function invoked
function invoked
function invoked
function invoked
RLEVector{Int64,Int64}
 Run values: [101, 102, 103]
 Run ends: [3, 5, 6]
```
Meanwhile, `map` is specialized to invode `simple_add` for 3 times (n runs).

```
julia> map(simple_add, x)
function invoked
function invoked
function invoked
RLEVector{Int64,Int64}
 Run values: [101, 102, 103]
 Run ends: [3, 5, 6]
```

**Comment by phaverty** [comment]
Thank you for this report. I'll be doing some work on this package during the winter break (last week in December).

**Comment by Marlin-Na** [comment]
I would be happy to help. Will make a PR if I am able to solve it.

于 2020年12月17日 GMT-05:00 下午11:37:16, Peter Haverty <notifications@github.com> 写到:
