### ISSUE TITLE
Developing with Julia@1.10

### ISSUE THREAD

**Issue by kentonvp** [phaverty/RLEVectors.jl#62]
Hi! I'd love to contribute to this package. I currently have julia@1.10 installed:
```julia
julia> VERSION
"v1.10.0"
```
I have forked the repository, but when I attempt to develop, I get the following warning
```julia
julia> using RLEVectors
┌ Warning: The active manifest file is an older format with no julia version entry. Dependencies may have been resolved with a different julia version.
└ @ ~/dev/RLEVectors.jl/Manifest.toml:0
```

I really want to tackle some of the issues, but cannot run anything unless I update the Manifest.toml using `Pkg; Pkg.upgrade_manifest()` and then after that, run a `Pkg.update()`.

Can I submit a PR to upgrade the Manifest.toml? or can the Manifest.toml be removed completely? (I know some projects do not include it in their repos.)

Thanks! Let me know if there is anything I can do.

**Comment by phaverty** [comment]
Awesome, I'd love to see that update. Please submit a PR. Thank you!

**Comment by kentonvp** [comment]
Done! #63

**Comment by phaverty** [comment]
Fixed by #63
@JuliaRegistrator register()

**Comment by phaverty** [comment]
@JuliaRegistrator register()

**Comment by phaverty** [comment]
Thanks, @kentonvp , I've included this change and I've also updated all the CI stuff.
